name: CD Front-end

on:
  workflow_dispatch:

jobs:

  ci:
    name: CI Workflow Main
    uses: ./.github/workflows/ci-backend-main.yml
    
  deploy:
    needs: ci
    runs-on: ubuntu-latest
    name: Deploy Netfire
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Instalação do cliente Netlify
        run: npm install -g @railway/cli
      - name: Deploy
        working-directory: back-end/
        run: railway up --detach --service sgcm_pedro_antonio
        env:
          RAILWAY_TOKEN: ${{ secrets.PEDRO_TOKEN }}
